### ISSUE TITLE
Tests fail if environment variables are not set

### ISSUE THREAD

**Issue by ztmeyer** [codeRIT/brickhack.io#537]
I noticed that `rake test` has 4 failures in these 2 files:
`test/controllers/manage/dashboard_controller_test.rb`
`test/controllers/mailer_test.rb`

Is this a concern? Is this something that could be punted to Hacktoberfest?

**Comment by sman591** [comment]
@ztmeyer which lines are failing for you? All tests are currently passing on [our Travis builds](https://travis-ci.org/codeRIT/brickhack.io/branches)

**Comment by ztmeyer** [comment]
Ah ok - strange, below is my local output. I haven't investigated them, was just curious if anyone else is seeing issues. If it's not a concern just ignore me :)

```
brickhack.io git:(bugfix/disable-rollbar-in-rake-tasks) rake test
Started with run options --seed 62777

ERROR["test_: upon slack invite email should deliver invite email. ", MailerTest, 3.2887340000015683]
 test_: upon slack invite email should deliver invite email. #MailerTest (3.29s)
ActionView::Template::Error:         ActionView::Template::Error: Slack invite URL missing
            app/views/mailer/slack_invite_email.html.erb:1:in `_app_views_mailer_slack_invite_email_html_erb___3868866962179432249_70219656267840'
            test/controllers/mailer_test.rb:115:in `block (2 levels) in <class:MailerTest>'
            test/controllers/mailer_test.rb:127:in `instance_exec'
            test/controllers/mailer_test.rb:127:in `block in create_test_from_should_hash'

ERROR["test_: upon successfull rsvp confirmation should deliver email to questionnaire. ", MailerTest, 3.459242999990238]
 test_: upon successfull rsvp confirmation should deliver email to questionnaire. #MailerTest (3.46s)
ActionView::Template::Error:         ActionView::Template::Error: Carpool link missing
            app/views/mailer/_getting_there.html.erb:7:in `_app_views_mailer__getting_there_html_erb___559489427694509863_70219670661980'
            app/views/mailer/rsvp_confirmation_email.html.erb:6:in `_app_views_mailer_rsvp_confirmation_email_html_erb__2536553415606103319_70219670683420'
            test/controllers/mailer_test.rb:36:in `block (2 levels) in <class:MailerTest>'
            test/controllers/mailer_test.rb:48:in `instance_exec'
            test/controllers/mailer_test.rb:48:in `block in create_test_from_should_hash'

ERROR["test_: upon application acceptance should deliver email to questionnaire. ", MailerTest, 3.49332000000868]
 test_: upon application acceptance should deliver email to questionnaire. #MailerTest (3.49s)
ActionView::Template::Error:         ActionView::Template::Error: Carpool link missing
            app/views/mailer/_getting_there.html.erb:7:in `_app_views_mailer__getting_there_html_erb___559489427694509863_70219670661980'
            app/views/mailer/accepted_email.html.erb:10:in `_app_views_mailer_accepted_email_html_erb__4115064956828466219_70219628339800'
            test/controllers/mailer_test.rb:70:in `block (2 levels) in <class:MailerTest>'
            test/controllers/mailer_test.rb:82:in `instance_exec'
            test/controllers/mailer_test.rb:82:in `block in create_test_from_should_hash'

ERROR["test_: while authenticated as an admin should allow access to all data endpoints. ", Manage::DashboardControllerTest, 6.021887000009883]
 test_: while authenticated as an admin should allow access to all data endpoints. #Manage::DashboardControllerTest (6.02s)
Groupdate::Error:         Groupdate::Error: Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql
            test/controllers/manage/dashboard_controller_test.rb:60:in `block (3 levels) in <class:DashboardControllerTest>'
            test/controllers/manage/dashboard_controller_test.rb:59:in `each'
            test/controllers/manage/dashboard_controller_test.rb:59:in `block (2 levels) in <class:DashboardControllerTest>'
            test/controllers/manage/dashboard_controller_test.rb:51:in `instance_exec'
            test/controllers/manage/dashboard_controller_test.rb:51:in `block in create_test_from_should_hash'

  498/498: [================================================================================] 100% Time: 00:00:09, Time: 00:00:09

Finished in 9.83097s
498 tests, 1089 assertions, 0 failures, 4 errors, 0 skips
```

**Comment by sman591** [comment]
Aha, I see now. The first three failures are due to environment variables, which the tests should probably take care of rather than relying on a `.env` file to be present (looks like that is also missing from the readme).

**Comment by sman591** [comment]
(Tapped on close by accident)

The last failure is due to a missing MySQL feature for time zones, which usually requires a short command to fix (the URL in the output should have the right instructions). A note should be added to the readme as well.

**Comment by sman591** [comment]
@ztmeyer I added a note to the README about running tests, including a first step of setting the `.env` file for environment variables.
